image: docker:stable
services:
  - docker:stable-dind

variables:
  IMAGE_VER: latest
  GITLAB_TAG: $CI_REGISTRY_IMAGE:$IMAGE_VER
  HUB_TAG: prantlf/git-p4:$IMAGE_VER

build:
  script:
    - |
      docker run --rm -i \
        -v "${PWD}"/.hadolint.yaml:/.config/hadolint.yaml \
        hadolint/hadolint < Dockerfile
    - docker build -t $GITLAB_TAG .
    - docker tag $GITLAB_TAG $HUB_TAG
    - echo -n "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $GITLAB_TAG
    - echo -n "$DOCKER_TOKEN" | docker login -u prantlf --password-stdin
    - docker push $HUB_TAG
  except:
    - tags
